### ISSUE TITLE
Coverage: Migrate to coveralls?

### ISSUE THREAD

**Issue by onerandomusername** [discord-modmail/modmail#112]
### Description
Codecov is deprecating its uploader. Rather than continue to use codecov, we should shift to coveralls.

However, due to coveralls often having outages, this should be set in the workflow to always exit this step with 0, even if there was a failure.

Its probably possible to do some chaining with echo and stuff, see https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions#about-exit-codes

There also is the underlying question, do we need to have coverage reported at all?

**Comment by Shivansh-007** [comment]
Would migrating to coveralls, lose all the coverage history we have in Codecov?

**Comment by onerandomusername** [comment]
Yes, but given how little coverage we've had up to this point, I don't think its worth blocking.

**Comment by Shivansh-007** [comment]
Right, I would be approving this issue, not because of the outages as they can happen to anyone and coveralls has experienced them in past not fairly regularly but yeah quite a few times, and rather because of codecov [deprecating](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) its uploader.

**Comment by onerandomusername** [comment]
I've been trialing this, and have managed to get coveralls outages to not cause the workflows to fail, which is a good thing IMO
