### ISSUE TITLE
chore: refactorlogging

### ISSUE THREAD

**Issue by onerandomusername** [discord-modmail/modmail#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues and there is no existing issue.

### Current Behavior

The code for logging is terrible. There's double formatters, a bunch of mess, and more.

### Expected Behavior

Less code.

### Steps To Reproduce

1. Pull the repo
2. Run the bot
3. Logs have a lot of unnecessary code.

### Select your hosting method

local hosting

**Comment by bast0006** [comment]
Yeah. I'm fixing this up. Deleted a chunk of code but most of it is just required--we want rotating loggers, so we gotta specify file, then durations, etc regardless of what we actually do. We can strip out some of the formatters though because coloredlogs automatically strips ascii codes when not logging to an interactive terminal.
